// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN9r5lKnvG2-DEgoKpFcFdEgWWy7Fx7Kw',
    appId: '1:151903926101:web:0cfb3c8357d8704f60e1dc',
    messagingSenderId: '151903926101',
    projectId: 'courses-e4848',
    authDomain: 'courses-e4848.firebaseapp.com',
    storageBucket: 'courses-e4848.appspot.com',
    measurementId: 'G-CK6V78ZKWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzoezrymNFIThG1CB9YaG9SuMdoM57aBE',
    appId: '1:151903926101:android:f751c1495592c71660e1dc',
    messagingSenderId: '151903926101',
    projectId: 'courses-e4848',
    storageBucket: 'courses-e4848.appspot.com',
  );
}
