name: courses
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  cloud_firestore: ^3.2.1
  drag_and_drop_lists: ^0.3.2+2
  file_picker: ^5.0.1
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  firebase_storage: ^10.3.4
  flutter:
    sdk: flutter
  flutter_quill: ^5.0.4
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  get_it: ^7.2.0
  go_router: ^4.1.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  provider: ^6.0.3
  tuple: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/logo.png
